#!/usr/bin/env bash
# This script is displaying "To infinity and beyond indefinitely. With a sleep 2 in between each iteration. I am invincible!!! when receiving a SIGTERM signal".


msg()
{
    echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2

done
